package com.entities;
// Generated 31 mai 2022, 12:54:16 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Etudiants generated by hbm2java
 */
@Entity
@Table(name = "etudiants", catalog = "smi", uniqueConstraints = @UniqueConstraint(columnNames = "cne"))
public class Etudiants implements java.io.Serializable {

	private Integer id;
	private Filiere filiere;
	private String nom;
	private String prenom;
	private String cne;
	private byte[] picture;

	public Etudiants() {
	}

	public Etudiants(Filiere filiere, String nom, String prenom, String cne, byte[] picture) {
		this.filiere = filiere;
		this.nom = nom;
		this.prenom = prenom;
		this.cne = cne;
		this.picture = picture;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_filier", nullable = false)
	public Filiere getFiliere() {
		return this.filiere;
	}

	public void setFiliere(Filiere filiere) {
		this.filiere = filiere;
	}

	@Column(name = "nom", nullable = false)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", nullable = false)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "cne", unique = true, nullable = false, length = 11)
	public String getCne() {
		return this.cne;
	}

	public void setCne(String cne) {
		this.cne = cne;
	}

	@Column(name = "picture", nullable = false)
	public byte[] getPicture() {
		return this.picture;
	}

	public void setPicture(byte[] picture) {
		this.picture = picture;
	}

}
