package com.entities;
// Generated 31 mai 2022, 02:26:55 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Filiere generated by hbm2java
 */
@Entity
@Table(name = "filiere", catalog = "smi", uniqueConstraints = @UniqueConstraint(columnNames = "code"))
public class Filiere implements java.io.Serializable {

	private Integer idFiliere;
	private User user;
	private String code;
	private String libille;
	private Set<Etudiants> etudiantses = new HashSet<Etudiants>(0);

	public Filiere() {
	}

	public Filiere(User user) {
		this.user = user;
	}

	public Filiere(User user, String code, String libille, Set<Etudiants> etudiantses) {
		this.user = user;
		this.code = code;
		this.libille = libille;
		this.etudiantses = etudiantses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_filiere", unique = true, nullable = false)
	public Integer getIdFiliere() {
		return this.idFiliere;
	}

	public void setIdFiliere(Integer idFiliere) {
		this.idFiliere = idFiliere;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "code", unique = true)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "libille")
	public String getLibille() {
		return this.libille;
	}

	public void setLibille(String libille) {
		this.libille = libille;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filiere")
	public Set<Etudiants> getEtudiantses() {
		return this.etudiantses;
	}

	public void setEtudiantses(Set<Etudiants> etudiantses) {
		this.etudiantses = etudiantses;
	}

}
